---
# tasks file for torlowski.configurator_nginx

#################################################
#               load variables                  #
#################################################

- name: 'check variables file'
  stat:
    path: '{{ role_path }}/vars/{{ ansible_distribution|lower }}.yml'
  register: stat_os_vars_file
  delegate_to: localhost
  connection: local
  tags: always

- name: 'load variables for os_distribution'
  include_vars:
    file: '{{ role_path }}/vars/{{ ansible_distribution|lower }}.yml'
  when: stat_os_vars_file.stat.exists
  tags: always

- name: 'check vault file'
  stat:
    path: '{{ role_path }}/vars/vault.yml'
  register: stat_os_vault_file
  delegate_to: localhost
  connection: local
  tags: always

- name: 'load encrypted vault variables'
  include_vars:
    file: '{{ role_path }}/vars/vault.yml'
  when: stat_os_vault_file.stat.exists
  tags: always

